### ISSUE TITLE
QRrecognizer

### ISSUE THREAD

**Issue by itsyoshio** [Schaggo/ESP-3D-Scanner#1]
Hi there,

Sorry to bother you.
This seems to contain a version of your Repo [QR Arduino](https://github.com/Schaggo/QR-ARDUINO.)
Would this be an improvement over the "old" repo or are those (ESP-3D-Scanner V6 and QR-ARDUINO) functionally the same?

Would you mind elaborating on why it's not possible to choose a higher resolution (>= SVGA) for QRrecognizer.

----

I'm having a hard time trying to recognize a "medium length" QR Code (containing an url with ~75 Chars).
For one i'm using the Ai-Thinker ESP32-S Cam, with the default OV2640 Lens it came with.

I'm able to get the Recognizer to actually detect when at ~12cm distance from my Smartphone.
Its really hard to get the Distance right to actually succeed in recognition, and then, it often fails at decoding (EEC).

What my Question boils down to : 
_Do you have some Guidance to better recognize the QR Code?_

**Comment by Schaggo** [comment]
Hi! 
Straight to your questions:

-The QR recognizer repo has no changes to the ESP-3D-Scanner.
-The resolution of the QR-functionality is limited by the actual processing power of the esp. 
-> There is just not enough beef on to use higher res. 
-> You could try to change the way the project works in a fashion, that you save an image on SD, and then apply the QR recognition. But I have no idea if that would work better.

- I successfully tested the scanner with strings containing 512 chars.
-> There are multiple possible causes for a char limit:

1) Let's start with optics. A lot of ESP-Cams come out of focus OOB. You mentioning a distance of 12 cm indicates that that might be the case. The datasheet for the "standard lens" mentions a 27 cm to infinity as the focal range. (there really is no standard lens, but let's use it as if there was one to have a starting point)
Upload the standard cam example to your module and try to focus the cam. A little contraption with a detailed flat object at a 27 cm distance should help a lot.

1b) Size/style of the QR code. Codes from my phone in black on white work well for me. 

2) Amount of error correction in your QR code. Depending on how you create the QR code, there may be several levels of error correction data in it - increasing the data by a lot.
I actually do not know if this QR project is capable of reading ECC QRs and if, to which degree. But anyway make sure, you have no error correction in your QR codes.

3) Memory. Try reading out free heap size and free SDRAM size to get an idea about how much memory is being used. In general, the QR scanner does not work well as a parallel process. For example, streaming and scanning while possible leads to a lot more errors in recognition.

I really only implemented this to have direct input for settings like SSID, PASS, IP address, etc. 
I don't think it would work in any dynamic way, like on a robot for navigation or similar complex functionality. 

If you have further trouble, I could look over your code.
